### ISSUE TITLE
Структура API библиотеки

### ISSUE THREAD

**Issue by Firebain** [Firebain/Pyvif#3]
Сейчас я опираюсь на такую структуру api (Закомментировано то, что пока не реализовано)

https://github.com/Firebain/Pyvif/blob/dbc4f1f38a4b40824fa64f25ee2c782e0e5219cc/main.py#L10-L27

Можете, пожалуйста, посмотреть этот код и сказать - все ли понятно и надо ли что нибудь изменить? 

### TODO

- [x] Поиск устройств в локальной сети
- [x] Авторизация в устройстве с помощью пароля и логина
- [x] Вызов методов onvif
- [x] Получение профилей камеры
- [x] Получение и изменение настроек профиля
- [x] Получение адреса потока профиля
